services:
  - type: web
    name: ecommerce-app
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.13.5
    autoDeploy: true